### ISSUE TITLE
Include numbers in influential answer section for criteria

### ISSUE THREAD

**Issue by dtdougherty** [shcaba/FishPath-updates#246] opened 2019-04-08 22:25 UTC
Criteria questions have been included in the influential answers section, however, they do not list a number next to them, like caveats. This makes it look like it doesn't impact any, until you click and see details.

**Comment by bsnouffer** [comment] 2019-04-09 06:34
Duplicate of #238

**Closed as completed by bsnouffer** 2019-04-09 06:34 UTC
Labels: Software functionality
