### ISSUE TITLE
Change Assessment Input-Based Category sort order from alphebetical to increasing complexity

### ISSUE THREAD

**Issue by serenalomonico** [shcaba/FishPath-updates#94] opened 2018-06-08 17:03 UTC
Locate Natalie's ordered list. This refers to the order of the categories themselves (Catch Only, Expert Judgement, etc.).

**Comment by bsnouffer** [comment] 2020-01-07 21:53
closing. duplicate of #201

**Closed as completed by bsnouffer** 2020-01-07 21:53 UTC
Labels: Software functionality, Assessment
