### ISSUE TITLE
Assessments: order of options when sorting by input/output category

### ISSUE THREAD

**Issue by NatalieDowling** [shcaba/FishPath-updates#272] opened 2019-07-01 17:51 UTC
When sorting by input or output category, it would be preferable to then order the categories by (approximately) least to most rigorous, as opposed to alphabetically. The obvious is to lead with the "Expert Judgement" category, and then the "Empirical Reference Points", followed by "Risk Assessments". We used to list options in this kind of order, and it's easier for users who are trying to understand the relative broad strength of options.

**Comment by bsnouffer** [comment] 2020-01-07 21:25
duplicate of #201

**Closed as completed by bsnouffer** 2020-01-07 21:25 UTC
