### ISSUE TITLE
Hide/Unhide issue in results display when user changes an answer

### ISSUE THREAD

**Issue by serenalomonico** [shcaba/FishPath-updates#262] opened 2019-05-16 14:59 UTC
SL: In Chile, we had issues with changing an answer in a completed questionnaire, but then the automatic “hiding” or greying out did not adjust to reflect changes. I believe the options that should have been “unhidden” with the new answer remained greyed out.

BS: In general that when answers change, what is automatically greyed out should update. One aspect that might pose some complications is when the updated answer affects an option that the user has explicitly hidden (or unhidden) vs what was done automatically. 

Think this through to implement fix.

**Comment by bsnouffer** [comment] 2019-05-29 01:06
I think this is a duplicate of #174

**Closed as completed by bsnouffer** 2019-05-29 01:06 UTC
Labels: Software functionality, Software bug/error
