### ISSUE TITLE
Question order and skipping bugs

### ISSUE THREAD

**Issue by dtdougherty** [shcaba/FishPath-updates#244] opened 2019-04-08 22:17 UTC
If we fill in the questionnaire in the order of management measure, assessment, data collection, both the data collection and MM sections numbering are off and there is a weird bug with the section completing and then you still have to go back in and answer several more questions after it says it is done.

**Comment by dtdougherty** [comment] 2019-04-18 20:52
This bug is more odd than first described. In later attempts to do the questionnaire, the questionnaire did not exit and then have us re-enter, but the ordering seems totally out of whack. I helped to reorder questions for the workshop in a spreadsheet (for spanish version), however, when they did it live, the order was different again.

**Comment by underbluewaters** [comment] 2019-05-28 16:33
I was able to reproduce a problem where I finished the assessment section, and then had to go back and answer this question:

<img width="1396" alt="Screen Shot 2019-05-28 at 9 25 00 AM" src="https://user-images.githubusercontent.com/511063/58494705-92063280-812a-11e9-806a-822cf108fabb.png">

I looks like hitting previous, and then next, will skip over a question! I think that's one source of the problem and should be pretty easy to fix.

I'm not sure about the order not matching the spreadsheet. I assume this spreadsheet matched the order in the new "Question Order" section of the admin interface? How different was the order. Are we talking about a question or two missing or out of order, or a major difference? Satisfied-by type questions and questions that have caveats and criteria relating to multiple sections can change how the order will appear in practice, but those only represent a few of the cases.

Another thought about not being about to page back-and-forth properly... There is a "finish mode" that is triggered when there are only a few questions left in a section. This means that if a question or two is added later, or somehow skipped, you only need to answer those questions and not page through the whole list in order. It may be that this finishing mode is being activated too often. I can change the settings to make it only trigger when 2-3 questions are left, and only when they are mixed with other questions that have already been answered. If they are at the end of the list anyways, we can just jump directly to them.

**Comment by bsnouffer** [comment] 2019-09-06 18:46
I am still seeing these issues when using the previous button in the questionnaire. Both issues seem to occur when hitting previous without selecting an answer. From initial testing it appears that selecting an answer, then hitting previous works as expected.

1) Now, sometimes hitting previous before selecting an answer will kick you out the questionnaire and have to reenter. It happened the first time I hit the previous button (on the 3rd question). On subsequent times, the previous button would bring me to the previous question, until I added a note. Then previous kicked me out again. 

2) If I didn't get kicked out of the questionnaire, hitting previous works as expected. However, clicking next will skip a question and move to the question after the one where I originally selected previous from. Each time hitting previous, then next will skip forward a question. 

For example:
- Viewing question 6
- Don't select any answer, Hit previous
- Viewing question 5 (doesn't matter whether or not changing answer here)
- Hit Next Question
- Viewing question 7

I need to do some more digging to find the underlying cause for why sometimes the behavior follows the first case vs the second.

**Comment by bsnouffer** [comment] 2020-01-29 17:25
I am able to reproduce workflow 1 by the following (albeit obscure seeming):
1) answer a couple questions
2) hit previous to get back to the first question
3) hit previous again from first question. This will bring you out of the questionnaire (as expected)
4) return to the questionnaire in the same section. This will start you at the first unanswered question.
5) hit previous. This bumps you out of the questionnaire instead of going back one question

**Comment by bsnouffer** [comment] 2020-01-29 18:30
Fixed in mcclintock-lab/FishPath#59

**Closed as completed by bsnouffer** 2020-01-29 18:30 UTC
Labels: Top Issue: Software, Software bug/error, Launch Issues, sprint-planning
